# Generated by Django 3.2.5 on 2021-07-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='api.user'),
            preserve_default=False,
        ),
    ]
